dist: bionic
language: ruby
rvm: 2.6
before_install:
  - export LIBTORCH_VERSION=1.3.1
  - ./test/ci/install_libtorch.sh
cache:
  bundler: true
  directories:
    - $HOME/libtorch
before_script: bundle exec rake compile -- --with-torch-dir=$HOME/libtorch/$LIBTORCH_VERSION
script: bundle exec rake test
notifications:
  email:
    on_success: never
    on_failure: change
