environment:
  matrix:
    - RUBY_VERSION: "26-x64"

cache:
  - vendor/bundle

install:
  - set PATH=C:\Ruby%RUBY_VERSION%\bin;%PATH%
  - bundle config --local path vendor/bundle
  - bundle install

build: off

before_build:
  - ruby -v
  - gem -v
  - bundle -v

build_script:
  - curl -fSL -o libtorch.zip https://download.pytorch.org/libtorch/cpu/libtorch-win-shared-with-deps-1.5.0.zip
  - unzip -q libtorch.zip
  - ridk enable
  - bundle exec rake compile -- --with-torch-dir=C:\projects\torch-rb\libtorch

test_script:
  - bundle exec rake test
