name: build
on: [push, pull_request]
jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
        - ruby: 2.6
          os: macos-10.15
    env:
      LIBTORCH_VERSION: 1.9.0
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - run: brew update
    - run: brew install libomp libtorch
    - run: bundle exec rake compile
    - run: bundle exec rake test
