name: build
on: [push, pull_request]
jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
        - ruby: 3.0
          os: macos-latest
    env:
      LIBTORCH_VERSION: 1.7.1
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - uses: actions/cache@v2
      with:
        path: ~/libtorch
        key: libtorch-${{ env.LIBTORCH_VERSION }}
      id: cache-libtorch-2
    - name: Download LibTorch
      if: steps.cache-libtorch.outputs.cache-hit != 'true'
      run: |
        cd ~
        wget -q -O libtorch.zip https://download.pytorch.org/libtorch/cpu/libtorch-macos-$LIBTORCH_VERSION.zip
        unzip -q libtorch.zip
    - run: bundle exec rake compile -- --with-torch-dir=$HOME/libtorch
    - run: bundle exec rake test
